@startuml

state EnCurso
state EnCurso2 as "EnCurso"

state descenderPieza as "descenderPieza()"{

  [*] -[#green]-> PIEZA_ACTIVA

  PIEZA_ACTIVA -[#green]-> PIEZA_ACTIVA : Tiempo solicita descenso / Pieza desciende una celda
  PIEZA_ACTIVA -[#green]-> PIEZA_FIJADA : Tiempo solicita descenso [colisión] / Pieza se fija en tablero
  PIEZA_FIJADA -[#green]-> PIEZA_FIJADA : [línea completa] / Línea eliminada\nLíneas superiores desplazadas\nPuntuación actualizada
  PIEZA_FIJADA -[#green]-> NUEVA_PIEZA_GENERADA : Nueva pieza generada\nPieza posicionada en centro superior

  state c <<choice>>

  NUEVA_PIEZA_GENERADA -[#green]-> c


}

c -[#red]-> Finalizado : [pieza no cabe] / Juego finalizado

EnCurso -d[#green]-> descenderPieza
  c -[#green]-> EnCurso2 : [pieza cabe] / Nuevo turno iniciado

Finalizado -[#red]-> [*]


@enduml
