@startuml

Juego "1" *-- "1" Tablero : "se juega en"
Juego "1" o-- "0..*" Pieza : "contiene piezas activas"
Juego "1" *-- "1..*" Turno : "se desarrolla en turnos"

Tablero "1" *-- "20" Linea : "compuesto por"

Pieza "*" --> "1" TipoPieza : "es de tipo"
Pieza "1" --> "1..4" Celda : "ocupa"

Turno "1" --> "1" Pieza : "involucra"
Turno "1" o-- "0..*" Movimiento : "permite"

Movimiento <|-- MovimientoAutomatico : "ejecuta"
Movimiento <|-- MovimientoDirigido : "permite"

Linea "1" *-- "10" Celda : "contiene"

@enduml